version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /storage
auth:
  token:
    realm: http://localhost:18080/service/token
    service: harbor-registry
    issuer: harbor-token-issuer
    rootcertbundle: /etc/registry_certs/root.crt
http:
  addr: :5000
  net: tcp
  headers:
    X-Content-Type-Options: [nosniff]
compatibility:
  schema1:
    enabled: true
notifications:
  endpoints:
    - name: harbor
      disabled: false
      url: http://harbor-core:8080/service/notifications
      timeout: 3000ms
      threshold: 5
      backoff: 1s
